### ISSUE TITLE
using .set doesn't trigger reactivity

### ISSUE THREAD

**Issue by andrewlorenz** [meteortemplates/array#5]
after initialising a reactiveArray, a later use of .set() in an event isn't triggering a re-evaluation of the associated helper to retrieve the array.  But a .push does work.

```
Template.example.onCreated(function() {
  this.sampleArray = new ReactiveArray(["this","that","other"]);
});

Template.example.helpers({
  sampleArray:function() {
    console.log("sampleArray helper");
    return Template.instance().sampleArray.get();
  }
});

Template.example.events({
  'click .change-array': function(event,template) {
    template.sampleArray.set(["fred","barry","andy"]);
  },
  'click .add-array': function(event,template) {
    template.sampleArray.push("another");
  }
});
```

when .add-array is clicked, the array is extended and the console.log fires.
when .change-array is clicked, the new contents of sampleArray aren't shown and the console.log doesn't fire.

In this example I have shown a simple array, but my real code actually implements an array of objects.

**Comment by jonjamz** [comment]
Ah this is probably due to the equality check:

https://github.com/meteortemplates/array/blob/master/templates:array.js#L32

**Comment by andrewlorenz** [comment]
I've got around it by going another way, I guess it would be nice to have a reactive array of objects but there's always 2 ways to skin cats!

**Comment by jonjamz** [comment]
In a quick test, _.isEqual does compare an array of objects, although I only tested with shallow objects.

Jon
